image: node

definitions:
  steps:
      - step: &compile
          caches:
            - node
          name: 'compile'
          condition:
            changesets:
              includePaths:
                - "src/**"
          script:
            - npm ci
            - npm run prebuild && npm run build
      - step: &lint
          caches:
            - node
          name: 'lint'
          condition:
            changesets:
              includePaths:
                - "src/**"
                - "test/**"
          script:
            - npm ci
            - npm run lint
      - step: &test
          caches:
            - node
          name: 'test'
          condition:
            changesets:
              includePaths:
                - "src/**"
          script:
            - npm ci
            - npm test
      - step: &buildNpush
          caches:
            - node
          name: 'build and push image to registry'
          services:
            - docker
          condition:
            changesets:
              includePaths:
                - "src/**"
                - "bitbucket-pipelines.yml"
          script:
            - IMAGE="cheguei.azurecr.io/$BITBUCKET_REPO_SLUG"
            - VERSION="latest" # "$BITBUCKET_BUILD_NUMBER"
            - echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY_HOST} --username ${REGISTRY_USERNAME} --password-stdin
            - docker build -t ${IMAGE} .
            - docker tag ${IMAGE} ${IMAGE}:${VERSION}
            - docker push ${IMAGE}:${VERSION}
      - step: &migration
          caches:
            - node
          name: 'Run Migration & Seeds'
          script:
            - npm ci
            - npm run knex:migrate && npm run knex:seed:run

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *test
        - step: *lint
        - step: *compile
  branches:
    dev:
      - step:
          <<: *buildNpush
          deployment: dev
    master:
      - step:
          <<: *buildNpush
    manual:
      - step:
          <<: *migration