version: '3.3'

services: 
  account:
    image: christianseki/account-service:latest
    ports:
      - "8280:8280"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    environment:
      - DATABASE_HOSTNAME
      - DATABASE_NAME
      - DATABASE_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - USE_PROXY_PREFIX=true
    networks:
      - public

networks:
  public:
    driver: overlay
    external: true