name: Deploy Infra
on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform init
        run: cd terraform && terraform init -input=false

      - name: Terraform validation
        run: cd terraform && terraform validate

      - name: Terraform plan
        run: cd terraform && terraform plan -input=false  

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Terraform init
      run: cd terraform && terraform init -input=false

    - name: Terraform validation
      run: cd terraform && terraform validate

    - name: Terraform apply
      run: cd terraform && terraform apply -auto-approve -input=false      
